title: "Automating Experimental Optics with Sample Efficient Machine Learning Methods"
description: "Sample-efficient machine learning methods for autonomous optical resonator alignment using reinforcement learning"
remote_theme: pages-themes/midnight@v0.2.0
baseurl: "/aqua"
url: "https://arindam5aha.github.io"

# Author information
author:
  name: "Arindam Saha"
  email: "arindam.saha@anu.edu.au"

# Social links
social:
  arxiv: "https://arxiv.org/abs/2503.14260"
  email: "arindam.saha@anu.edu.au"

# GitHub Pages settings
github:
  repository_url: "https://github.com/arindam5aha/aqua"

# Jekyll settings - keep minimal for GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# File handling
include:
  - Final_Plots_files

exclude:
  - README.md
  - Gemfile*
  - node_modules
  - vendor

# SEO
lang: en-US