title: "The AQUA Project"
description: "Automating Experimental Optics with Sample Efficient Machine Learning Methods"
remote_theme: pages-themes/midnight@v0.2.0
baseurl: ""
url: "https://theaquaproject.github.io"

# Author information
author:
  name: "Arindam Saha"
  email: "arindam.saha@anu.edu.au"

# Social links
social:
  arxiv: "https://arxiv.org/abs/2503.14260"
  email: "arindam.saha@anu.edu.au"

# GitHub Pages settings
github:
  repository_url: "https://github.com/theaquaprojekt/theaquaprojekt.github.io"

# Jekyll settings - keep minimal for GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# File handling
include:
  - optics_assets
  - assets

exclude:
  - README.md
  - Gemfile*
  - node_modules
  - vendor

# SEO
lang: en-US