title: The Aqua Project
description: Building a generalist control agent for every experiment on the planet
remote_theme: pages-themes/midnight@v0.2.0
markdown: kramdown
baseurl: "/aqua"
css: assets/style.scss
url: "https://arindam5aha.github.io/aqua"
author:
  name: "Arindam Saha"
  email: "arindam.saha@anu.edu.au"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
kramdown:
  -  input: Kramdown
  -  syntax_highlighter: coderay
  -  math_engine: mathjax
  -  math_engine_opts: 
      mathjax: 
        macros: 
          "\\R": "\\mathbb{R}"
          "\\N": "\\mathbb{N}"
          "\\Z": "\\mathbb{Z}"
          "\\Q": "\\mathbb{Q}"
          "\\C": "\\mathbb{C}"
        display_math: true
        preview: true
        no_inline_math_dollars: true
        no_mathjax: false
  -  syntax_highlighter_opts: 
      coderay:
        line_numbers: true
        line_number_start: 1
        wrap: span
        css: class
        tab_width: 2
        coderay_wrap: span
        coderay_line_numbers: true
        coderay_line_number_start: 1
        coderay_tab_width: 2
  -  line_numbers: table
  -  bold_every: 5
exclude:
  - README.md
